// <auto-generated />
using System;
using Ap12Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ap12Web.Migrations
{
    [DbContext(typeof(Ap12WebDbContext))]
    [Migration("20260209150002_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ap12Web.Models.Hersteller", b =>
                {
                    b.Property<int>("HerstellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerstellerId"));

                    b.Property<DateTime>("EingefügtAm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("HerstellerId");

                    b.ToTable("Hersteller");
                });

            modelBuilder.Entity("Ap12Web.Models.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktId"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("EingefügtAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("HerstellerId")
                        .HasColumnType("int");

                    b.Property<double>("Preis")
                        .HasColumnType("float");

                    b.HasKey("ProduktId");

                    b.HasIndex("HerstellerId");

                    b.ToTable("Produkte");
                });

            modelBuilder.Entity("Ap12Web.Models.Produkt", b =>
                {
                    b.HasOne("Ap12Web.Models.Hersteller", "Hersteller")
                        .WithMany("Produkte")
                        .HasForeignKey("HerstellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hersteller");
                });

            modelBuilder.Entity("Ap12Web.Models.Hersteller", b =>
                {
                    b.Navigation("Produkte");
                });
#pragma warning restore 612, 618
        }
    }
}
