// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonenVerwaltung.Data;

#nullable disable

namespace PersonenVerwaltung.Migrations
{
    [DbContext(typeof(PersonenDbContext))]
    [Migration("20251029123446_MehrZeichen")]
    partial class MehrZeichen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonenVerwaltung.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("Alter")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StandortId")
                        .HasColumnType("int");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId");

                    b.HasIndex("StandortId");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("PersonenVerwaltung.Models.Standort", b =>
                {
                    b.Property<int>("StandortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandortId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StandortId");

                    b.ToTable("Standorte");
                });

            modelBuilder.Entity("PersonenVerwaltung.Models.Person", b =>
                {
                    b.HasOne("PersonenVerwaltung.Models.Standort", "Standort")
                        .WithMany("Personen")
                        .HasForeignKey("StandortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Standort");
                });

            modelBuilder.Entity("PersonenVerwaltung.Models.Standort", b =>
                {
                    b.Navigation("Personen");
                });
#pragma warning restore 612, 618
        }
    }
}
